name: deviantart_client
description: A client for the DeviantArt API.
version: 1.0.0
repository: https://github.com/tyler-conrad/deviantart_client.git

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5
  http: ^1.2.2
  logger: ^2.4.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
